config/routes.rb
MadisonRuby::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraints(:host => /madisonruby.com/) do
    root :to => redirect("http://madisonruby.org")
    match '/*path', :to => redirect {|params| "http://madisonruby.org/#{params[:path]}"}
  end

  match 'apply_to_be_a_sponsor' => "pages#apply_to_be_a_sponsor", :as => "apply_to_be_a_sponsor"
  match 'cfp' => "pages#call_for_proposals", :as => "cfp"
  match 'home' => "pages#home", :as => "home"
  match 'policies' => "pages#policies", :as => "policies"
  match 'register' => "pages#register", :as => "register"
  match 'schedule' => "pages#schedule", :as => "schedule"
  match 'speakers' => "pages#speakers", :as => "speakers"
  match 'sponsors' => "pages#sponsors", :as => "sponsors"
  match 'travel' => "pages#travel", :as => "travel"
  match 'hotels/doubletree' => 'pages#doubletree', :as => "doubletree"
  #match 'hotels/hyatt_place' => 'pages#hyatt_place', :as => "hyatt_place"
  #match 'hotels/inn_on_the_park' => 'pages#inn_on_the_park', :as => "inn_on_the_park"
  #match 'hotels/sheraton' => 'pages#sheraton', :as => "sheraton"
  match 'posts/2011-07-25-Conference-Error-in-Your-Favor-Collect-225' => 'pages#bank_error', :as => "bank_error"
  match 'posts/2011-08-05-After-Party-Details-Announced' => 'pages#after_party', :as => "after_party"
  match 'what_to_expect' => "pages#what_to_expect", :as => "what_to_expect"

  unless Rails.env.production?
    match 'ui(/:action)', controller: 'ui'
  end

  root to: 'pages#home'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  def anchor
    name.underscore.gsub(' ', '_') if self.name
  end

  def image_path
    self.regular_image_path
  end

  def has_website?
    website_url.present?
  end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :load_footer_sponsors

  def home
    @speakers = Speaker.where(Speaker.arel_table[:homepage_image_path].not_eq('')).where(Speaker.arel_table[:homepage_image_path].not_eq(nil)).shuffle[0..9]
  end

  def speakers
    @speakers = Speaker.all
  end

  def sponsors
    @sponsors = Sponsor.all.sort_by {|s| s.ranking }
  end
private
  def load_footer_sponsors
    @footer_sponsors = Sponsor.all.sort_by {|s| s.ranking }.chunk {|s| s.ranking }
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  layout false
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title
      = yield :page_title
    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}/
    %link{:href => "/favicon.ico", :rel => "icon", :type => "image/x-icon"}/
    %meta(charset="UTF-8")
    = stylesheet_link_tag "application"
    = javascript_include_tag 'jquery'
    = include_fancy_box
    = yield :head

    %script{:type=>"text/javascript", :src=>"http://use.typekit.com/uob4zuw.js"}
    :javascript
      try{Typekit.load();}catch(e){}

  %body
    %header
      %section
        %h1= link_to "Madison Ruby", "/"
        %nav
          %ul
            %li= link_to "Home", '/'
            %li= link_to "Speakers", speakers_path
            %li= link_to "Schedule", schedule_path
            %li= link_to "Sponsors", sponsors_path
            %li= link_to "Travel", travel_path
            %li.register= link_to "Register", "http://2013.madisonruby.org"
        %p
          %mark(data-after_content="$") Workshops - August 22, 2013
          %mark(data-after_content="$") Conference - August 23-24, 2013
          Madison, WI
    #masthead
      %p.notice= notice
      %p.alert= alert
      .register
        %h1 Madision Ruby Conference
        %p
          Discover a hidden
          %strong gem
          in Madison, Wisconsin
        = link_to "http://2013.madisonruby.org" do
          %span Register Now
    #content
      = yield

    %footer
      %p
        != "Copyright &copy; 2011-2013 Madison Ruby Conference &mdash; "
        = mail_to "contact@madisonruby.org"
        != "&mdash; "
        = link_to "Policies", policies_path

    :javascript
      var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
      document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

      try{
      var pageTracker = _gat._getTracker("UA-17866845-1");
      pageTracker._trackPageview();
      } catch(err) {}

      var woo_settings = {idle_timeout:'300000', domain:'madisonruby.org'};
      var woo_actions = [{type:'pageview',url:window.location.pathname+window.location.search,title:document.title}];
      (function(){
      var wsc = document.createElement('script');
      wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
      wsc.type = 'text/javascript';
      wsc.async = true;
      var ssc = document.getElementsByTagName('script')[0];
      ssc.parentNode.insertBefore(wsc, ssc);
      })();

app/views/pages/2011/schedule.html.haml
- content_for :page_title do
  Schedule - Don't Miss Anything - August 18-20, 2011 - Madison, WI

%section#schedule
  %h1 Our Schedule

  %h2 Saturday, August 20, 2011
  %table{ :cellspacing => 0}
    %thead
      %tr
        %th &nbsp;
        %th
          %h3 Playhouse
        %th
          %h3 Wisconsin Studio

    %tr
      %td.slot 9:00 - 10:30AM
      %td.plenary{ colspan: '2' }
        Coffee

    %tr
      %td.slot 9:15 - 10:15AM
      %td.talk.plenary{ colspan: '2' }
        Growing a Software as a Service Application Panel
        .name
          = link_to "Barry Hess", speakers_path(anchor: 'barry_hess')
          , Harvest / 
          = link_to "Jason McCay", speakers_path(anchor: 'jason_mccay')
          , MongoHQ / Chris Mathieu, Tropo - Moderated by Steven Bristol

    %tr
      %td.slot 10:15 - 10:30AM
      %td.plenary{ colspan: '2' }
        Break

    %tr
      %td.slot 10:30 - 11:00AM
      %td.talk
        Code as Literature
        .name
          = link_to "Steve Klabnik", speakers_path(anchor: 'steve_klabnik')
      %td.talk.studio
        "Consultants &amp; Rockstars, Who needs 'em"
        .name
          = link_to "Lori Olson", speakers_path(anchor: 'lori_olson')

    %tr
      %td.slot 11:00 - 11:10AM
      %td.plenary{ colspan: '2'} Stretching

    %tr
      %td.slot 11:00 - 11:30AM
      %td.plenary{ colspan: '2' }
        Break

    %tr
      %td.slot 11:30 - 12:10PM
      %td.talk
        "Have Fun the Rong Way"
        .name
          = link_to "Matt Yoho", speakers_path(anchor: 'matt_yoho')
        Blow Up Your Views
        .name
          = link_to 'Jeff Casimir', speakers_path(anchor: 'jeff_casimir')
      %td.talk.studio
        Lightning Talks

    %tr
      %td.slot 12:00 - 1:30PM
      %td.plenary{ colspan: '2' }
        Lunch on Engine Yard

    %tr
      %td.slot 1:30 - 2:00PM
      %td.talk
        "Building the Great Wall: API Driven Applications"
        .name
          = link_to "Dan Melnick & Scott Parker", speakers_path(anchor: 'dan_melnick')
      %td.talk.studio
        "MongoMapper Migrations - Handling Changes With No Schema"
        .name
          = link_to 'Tim Connor', speakers_path(anchor: 'tim_connor')

    %tr
      %td.slot 2:00 - 2:10PM
      %td.plenary{ colspan: '2'} Stretching

    %tr
      %td.slot 2:00 - 2:30PM
      %td.plenary{ colspan: '2' }
        Break

    %tr
      %td.slot 2:30 - 3:00PM
      %td.talk
        "Whose Wife Are You?"
        .name
          = link_to 'Renée Devoursney', speakers_path(anchor: 'renee_de_voursney')
      %td.talk.studio
        "Kick Your Project in the Mouth"
        .name
          = link_to 'Collin Schaafsma', speakers_path(anchor: 'collin_schaafsma')

    %tr
      %td.slot 3:00 - 3:30PM
      %td.plenary{ colspan: '2' }
        Coffee Break

    %tr
      %td.slot 3:30 - 4:00PM
      %td.talk
        "Who, What, Where, When, Why, and How to Test"
        .name
          = link_to 'Jon Larkowski', speakers_path(anchor: 'jon_larkowski')
      %td.talk.studio
        "Creating RubyGems from Scratch"
        .name
          = link_to 'Brian Hogan', speakers_path(anchor: 'brian_hogan')

    %tr
      %td.slot 4:00 - 4:30PM
      %td.plenary{ colspan: '2' }
        Break

    %tr
      %td.slot 4:30 - 5:00PM
      %td.talk
        What Makes JRuby Different?
        .name
          = link_to 'Charlie Nutter', speakers_path(anchor: 'charlie_nutter')
      %td.talk.studio
        "CSS Workflow With Sass"
        .name
          = link_to 'Jina Bolton', speakers_path(anchor: 'jina_bolton')

    %tr
      %td.slot 5:00 - 5:15PM
      %td.plenary{ colspan: '2' }
        Break

    %tr
      %td.slot 5:15 - 5:45PM
      %td.talk
        Tip of the Skinny Iceberg
        .name
          = link_to "Stephen Caudill", speakers_path(anchor: 'stephen_caudill')
          , Hashrocket

      %td.talk.studio
        The Ruby Environment
        .name
          Brad Grzesiak

    %tr
      %td.slot 5:45 - 6:30PM
      %td.talk.plenary{ colspan: '2' }
        Testing Panel
        .name
          Corey Haines, Panelist
        .name
          Jon Larkowski, Panelist
        .name
          Bryan Liles, Panelist
        .name
          Chad Pytel, Panelist
        .name
          Steven Bristol, Moderator

    %tr
      %td.slot 6:15 - 6:30PM
      %td.plenary{ colspan: '2' }
        End of day announcements
        .name
          Jim Remsik &amp; Robert Pitts

    %tr
      %td.slot 6:30 - 8:00PM
      %td{ colspan: '2' }
        Dinner - Self Organized

    %tr
      %td.slot
        8:00 - 11:00PM
        %br/
        (Venue Curfew)
      %td.talk{ colspan: '2' }
        Conference After Party - MMoCA Rooftop Sculpture Garden
        %ul
          %li.name
            Giles Bowkett
          %li.name
            = link_to "Dosh (a.k.a. Martin Dosh)", 'http://en.wikipedia.org/wiki/Dosh'
          %li.name
            Rob Sanheim

= render :partial => 'sponsors'

app/views/pages/_call_for_proposals.html.haml
%h2.call_attention
  The
  = link_to "Call for Proposals", cfp_path
  is open until May 31st, 2013.

app/views/pages/_sponsor.html.haml
%a{ :name => sponsor.name.downcase }
%article
  %aside
    %dl
      %dt.company Company:
      %dd= link_to sponsor.name, sponsor.url
      - if sponsor.twitter_handle.present?
        %dt.twitter Twitter:
        %dd= link_to "@#{sponsor.twitter_handle}", "http://twitter.com/#{sponsor.twitter_handle}"
      %dt.website Website:
      %dd= link_to sponsor.url, sponsor.url

  = image_tag sponsor.image_path, alt: sponsor.name
  .bio
    %hgroup
      %h1= sponsor.name

    %p= sponsor.description.html_safe if sponsor.description

app/views/pages/_sponsor_logo.html.haml
= link_to image_tag(sponsor.image_path, alt: sponsor.name), sponsor.url, :target => "_blank"

app/views/pages/_sponsors.html.haml
%section#sponsors
  %h1 Sponsors
  %ul
    - @footer_sponsors.each do |level, sponsors|
      %li
        .level
          = render :partial => 'sponsor_logo', :collection => sponsors, :as => :sponsor

app/views/pages/home.html.haml
- content_for :page_title do
  Madison Ruby Conference - Aug 22-24, 2013 - Madison, WI

- content_for :head do
  = render :partial => 'get_satisfaction'

= render :partial => 'call_for_proposals'

%section#intro
  %article
    %p Madison Ruby Conference is a more than one track conference committed to bringing together two great communities.  The conference will showcase to locals the assets of the Ruby community and allow visitors to Madison a chance to experience one of the best, brainiest, and least expensive places in the US to live and work.
    %p= link_to "Register Now ▸", "http://2013.madisonruby.org", class: "more"
  %article.speakers
    %header
      %h1 Our Speakers
      = link_to "View All ▸", speakers_path, class: "more"

    %ul
      - @speakers.each do |speaker|
        %li= link_to image_tag("#{speaker.homepage_image_path}", alt: speaker.name), speakers_path(anchor: speaker.anchor)

%section#workshops
  %h1 Our Workshops
  %p Need to brush up on Ruby or related technologies? Get a jumpstart just before the conference with world-class workshops by leaders in the community. These one day classes will give you to tools and connections you need to get started or get to the next level. Classes will run from 9:00 AM to 5:30 PM and lunch will be provided.

  -# %article
    = image_tag "logo_github.png", alt: "GitHub: Advanced Git"
    %h1 Advanced Git with Matthew McCullough
    %p This full day Git workshop takes you beyond the basic edit, add, and commit workflow to deep Git features that benefit developers appreciative of what Git's flexible DVCS model brings to hard-core software development. You'll learn how to harvest and inspect commit-specific merges, leverage interactive rebase, and search through history with precision and speed. Tags, GPG signatures, and other cryptographic integrity features will become clear, and pushing and pulling will be controlled with newfound precision.

    %p This workshop requires attendees to have basic to intermediate level familiarity with Git.

  -# %article
    = image_tag "logo_railsbridge.png", alt: "RailsBridge"
    %h1 RailsBridge Womens Outreach Workshop
    %p The target audience is anyone who has a laptop computer and is willing to devote a Wednesday evening and full day on Thursday to learning how to develop a web application using the popular Ruby on Rails framework.

    %p
      This workshop is intended to reach out to women (of all skill levels) who are interested and / or new to Ruby and Rails.

      In this workshop, we'll take you through building a complete web application using Ruby on Rails. By the end of the workshop, you'll have an application on the internet that connects to a database and reads and writes information.

      Registration for this free workshop is now open.

    %p= link_to "Join Mad-Railers to Register", "http://www.meetup.com/Mad-Railers/", :class => "join-mad-railers"

  -# %article
    = image_tag "logo_jumpstart_lab.png", alt: "Ruby Jumpstart"
    %h1 Introduction to Ruby with Jeff Casimir

    %p If you’re looking for your first introduction to programming this is the course for you. You’ll jump right in write code. The Level 1 course is an introduction to Ruby, data structures, flow control, conditions, basic I/O, and manipulating data. No prior programming experience is necessary.

    %p We'll work on an "Extract-Translate-Load" (ETL) project, starting with a file full of spreadsheet data, manipulating individual elements, generating form letters, and looking up Congressional district data via a web-based API.

  -# %article
    = image_tag "logo_wynn_adam.png", alt: "Wynn Netherland & Adam Stacoviak"
    %h1 Design Eye for The Dev Guy or Gal
    %ul
      %li Part 1: Objectifying design
      %li Part 2: Dive into CSS3 and HTML5
      %li Part 3: Introducing Sass
      %li Part 4: Putting it all together with Compass

%section#sidebar
  %article
    %h1 Killer After-Party!
    %p When surveyed, the locals had many suggestions for putting on a great event but, there was one unanimous suggestion: A Killer After-Party.  We listened. We are putting together an epic  bash to celebrate the success of this event.  The after-party will be held at the rooftop sculpture garden of the Museum of Contemporary Art.  The soundtrack will be provided by a mix of local musicians from the Madison and Ruby communities.
    -# %p= link_to "View More ▸", "#", class: "more"
  %article
    <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FMadison-Ruby%2F115398258538061&amp;width=292&amp;colorscheme=light&amp;show_faces=false&amp;stream=false&amp;header=false&amp;height=62" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:62px;" allowTransparency="true"></iframe>
  %article
    %h1 Overheard
    <script src="http://widgets.twimg.com/j/2/widget.js"></script>
    :javascript
      new TWTR.Widget({
        version: 2,
        type: 'search',
        search: '@madisonruby',
        interval: 6000,
        title: '',
        subject: 'Overheard',
        width: 'auto',
        height: 300,
        theme: {
          shell: {
            background: '#ffffff',
            color: '#a60e13'
          },
          tweets: {
            background: '#ffffff',
            color: '#444444',
            links: '#a60e13'
          }
        },
        features: {
          scrollbar: true,
          loop: false,
          live: true,
          hashtags: true,
          timestamp: true,
          avatars: true,
          toptweets: true,
          behavior: 'all'
        }
      }).render().start();

%section#workshops
  %h1 Our Venue
  = link_to(image_tag("overture-logo-475px.png", alt: "Overture Center for the Arts"), 'http://www.overturecenter.com')
  %p In 1998, local businessman W. Jerome Frautschi made a breathtaking, multimillion dollar commitment for the development of a cultural arts district in downtown Madison. The Overture Foundation was established to solve the space needs of the city's major arts organizations, and internationally famous architect Cesar Pelli designed the project.

  %p
    Madison Ruby is taking over this venue for three days.  Using everything from breakout rooms, such as
    = link_to 'Rotunda Studio', 'http://www.overturecenter.com/about/venues/rotunda-studio'
    and
    = link_to 'Wisconsin Studio', 'http://www.overturecenter.com/about/venues/wisconsin-studio'
    to the three-hundred and fifty seat
    = link_to 'Playhouse Theater', 'http://www.overturecenter.com/about/venues/the-playhouse'
    we have a visually striking environment to inspire and engergize our attendees.

%section#sidebar
  %article
    %h1 How To Get Here
    %p
      Overture Center for the Arts
      %br/
      201 State Street, Madison, WI
    <iframe width="325" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=201+State+Street,+Madison,+WI&amp;aq=2&amp;sll=37.0625,-95.677068&amp;sspn=55.806079,63.984375&amp;ie=UTF8&amp;hq=&amp;hnear=201+State+St,+Madison,+Wisconsin+53703&amp;t=h&amp;z=14&amp;ll=43.074727,-89.388088&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=201+State+Street,+Madison,+WI&amp;aq=2&amp;sll=37.0625,-95.677068&amp;sspn=55.806079,63.984375&amp;ie=UTF8&amp;hq=&amp;hnear=201+State+St,+Madison,+Wisconsin+53703&amp;t=h&amp;z=14&amp;ll=43.074727,-89.388088" style="color:#0000FF;text-align:left">View Larger Map</a></small>

= render :partial => 'sponsors'

app/views/pages/inn_on_the_park.html.haml
#hotel
  %h1 Best Western Inn on the Park

  %p An urban landmark on the Capitol Square in Madison, the hotel is located directly across from the State Capitol building. The Capitol Square is home to such popular seasonal attractions as the Dane County Farmer’s Market, Art Fair on the Square and Concerts on the Square. Only blocks from the University of Wisconsin, Madison campus, Frank Lloyd Wright inspired Monona Terrace, and Overture Center of the Arts,the Inn on the Park is the best way to experience the best of Madison.

  %h2 Best Western Inn on the Park

  = link_to 'http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=22+South+Carroll+Street,+Madison,+WI&aq=0&sll=43.04684,-89.374211&sspn=0.012357,0.027874&ie=UTF8&hq=&hnear=22+S+Carroll+St,+Madison,+Wisconsin+53703&t=h&z=16' do
    %p
      22 South Carroll Street
      %br
      Madison, WI 53703

  %h3 Hotel Reservations

  %p We have been given an exceptional group rate by the Best Western Inn on the Park for Madison Ruby Conference attendees. Book your room early, as the Conference room block will sell out. 

  %ul
    %li $119* per night for rooms with one bed (1-2 people)
    %li $129* per night for rooms with two beds (1-4 people)
    %li $159* per night for suites

  %p *In addition to these rates there will be an $8.00 per person, per day increase for the continental breakfast coupons.  There is a two night minimum stay requirement for any reservations staying Friday or Saturday.  Complimentary High-speed internet in all guest rooms.

  %p Room rates are subject to any local, state, and federal tax that may apply at time of occupancy. (For informal purposes only, currently the room tax rate is 14.5% in effect at the time of check-in.)  Guests who are tax-exempt must provide certificate.

  %h3 To Make a Reservation

  %ul
    %li
      %strong By Phone:
      To receive the special discounted room rate, please identify yourself as being part of the “Madison Ruby Conference 2012 Block.”
      %ul
        %li
          %strong Direct Number:
          608-285-8000
        %li
          %strong Toll Free Reservation Number:
          800-279-8811
  %p Reservations received after the room block sells out will be based on availability, and/or at the Hotel’s prevailing rates if the hotel is close to selling out.  All reservations will require a 1-night advance deposit per room, plus tax, to guarantee accommodations. All advance reservation deposits are completely refundable if canceled 24 hours before arrival to avoid cancelation penalties.

  %h2 Getting to the Inn on the Park from Dane County Regional Airport

  %p There are a number of ways to get from the airport to the Best Western Inn on the Park:

  %ul
    %li
      %strong Courtesy Hotel Shuttle:
      Call to arrange
    %li
      %strong Taxi:
      with a minimum charge about $15 USD
    %li
      %strong Bus:
      Base Fare $2.00
      %ol
        %li Be ready to board route #20 North Transfer Point via Airport at Arrivals 6 [9169] by quarter past the hour or quarter to the hour. (about a 10 minute ride)
        %li Exit at stop Arrival North Transfer Point [5101]. (about a 5 minute wait)
        %li Make your way to stop North Transfer Point Huxley [5100], if different from where you exit, by the top or bottom of the hour to board route #2 West Transfer Point (no cost with transfer pass from driver). (about a 22 minute ride)
        %li Exit at destination stop Mifflin & Carroll [1310].
        %li Walk 2 blocks following Carroll to Main Street.  Inn on the Park will be on the corner. 
    %li
      %strong Rental Car:
      prices vary and cars are available at the airport
    %dl
      %dt Driving Directions
      %dd Take International Lane from airport terminal. Turn left on Packers Avenue at end of International Lane. Turn left onto First Street (second set of lights) and go two blocks. Turn right onto East Washington and take it up to the State Capitol. Follow right around Capitol Square. Hotel is located just past West Washington Avenue.

  %h3 Parking

  %p
    Free valet parking

app/views/pages/policies.html.haml
- content_for :page_title do
  Madison Ruby Policies Page

%section#articles
  %article
    %a{ name: 'cancellation' }
    %hgroup
      %h1 Cancellation Policy
    %h2.call_attention
      *** All ticket sales are final and non-refundable. ***
    %p
      You may transfer your registration to another person by August 21, 2012 by providing authorization to us at contact@MadisonRuby.org.
    %br
    %p
      In the unlikely event that the conference is canceled, the liability to Madison Ruby is limited to the returning paid registration fees.
    %br
    %p{ style: 'padding-bottom: 50px' }
      Please contact us at contact@MadisonRuby.org regarding registration questions or concerns.

= render :partial => 'sponsors'

app/views/pages/schedule.html.haml
- content_for :page_title do
  Schedule - Don't Miss Anything - August 23-25, 2012 - Madison, WI

%section#schedule
  %h1
    %p
      Our Schedule can be seen on
      = link_to "Sched.org", "http://madisonruby2012.sched.org/"

= render :partial => 'sponsors'

app/views/pages/sponsors.html.haml
- content_for :page_title do
  Sponsors - Helping Our Community - August 23-25, 2012 - Madison, WI

%h2.call_attention
  We still have opportunities available for you to gain exposure and enhance the conference for attendees.
  %br
  %br
  = link_to "Apply to be a sponsor!", apply_to_be_a_sponsor_path

%br

%section#sponsors
  %h1 Our Sponsors

  = render :partial => 'sponsor', collection: @sponsors

app/views/pages/travel.html.haml
- content_for :page_title do
  Hotel and Travel Information for Madison Ruby - August 23-25, 2012

%section#travel

  %a{ :name => 'doubletree' }
  %article
    %aside
      %dl
        %dt.company Address:
        %dd= link_to "525 West Johnson Street, Madison, WI 53703", "http://goo.gl/maps/eb61O"
        %dt.website Website:
        %dd= link_to "Doubletree Booking", "http://doubletree.hilton.com/en/dt/groups/personalized/M/MSNDTDT-MRB-20130821/index.jhtml?WT.mc_id=POG"
        %dt.phone Direct Number:
        %dd 608-251-5511
        %dt.phone Toll Free Reservation Number:
        %dd 800-222-TREE

    .bio
      %hgroup
        %h1 DoubleTree by Hilton Hotel Madison

      %p
        Right in the heart of downtown Madison, DoubleTree by Hilton Hotel Madison is close to the eastern edge of the University of Wisconsin-Madison campus, nestled between Lake Monona and Lake Mendota.

      .more_details
        = link_to 'More details', doubletree_path

  %a{ :name => 'madison_hostel' }
  %article
    %aside
      %dl
        %dt.company Address:

        %dd= link_to "141 S Butler St, Madison, WI", "http://maps.google.com/maps/place?cid=566553957758048622&q=Madison+Hostel,+South+Butler+Street,+Madison,+WI&hl=en&sll=43.075143,-89.37902&sspn=0.006295,0.006295&ie=UTF8&ll=43.081317,-89.392962&spn=0,0&t=h&z=16"
        %dt.website Website:
        %dd= link_to "Hostelling Int'l Madison", "http://www.hiusa.org/madison"

      %h1 Rate Card

      %dl
        %dt One Bed
        %dd $18
    .bio
      %hgroup
        %h1 Madison Hostel

      %p
        Hostels are not for everyone and this one has common rooms and showers that might not be your cup of tea. However if you can get past a few details like that you can meet some excellent folks travelling the world and get your own bed to crash on for less than a dinner for two.

      = link_to_image "madison-hostel-exterior-thumb.jpg:madison-hostel-exterior-large.jpg", :title => "Madison Hostel Exterior", :class => 'fancy'
      = link_to_image "madison-hostel-dining-thumb.jpg:madison-hostel-dining-large.jpg", :title => "Madison Hostel Dining Room", :class => 'fancy'
      = link_to_image "madison-hostel-common-room-thumb.jpg:madison-hostel-common-room-large.jpg", :title => "Madison Hostel Common Room", :class => 'fancy'